CC = gcc
CFLAGS = -Wall -Wextra

# Lista de archivos fuente
SOURCES = shell.c mkdir.c ls.c rmdir.c touch.c cat.c chmod.c rmfile.c

# Objetos generados a partir de los archivos fuente


# Nombres de los ejecutables
EXECUTABLES = shell mkdir ls rmdir touch cat chmod rmfile




# Regla para construir todos los ejecutables
all: $(EXECUTABLES)



	
	

# Regla para limpiar los y ejecutables
clean:
	rm -f $(EXECUTABLES)
