CC = gcc
CFLAGS = -Wall -Wextra

# Lista de archivos fuente
SOURCES = shell.c mkdir.c ls.c rmdir.c touch.c cat.c chmod.c

# Objetos generados a partir de los archivos fuente


# Nombres de los ejecutables
EXECUTABLES = shell mkdir ls rmdir touch cat chmod

# Regla para compilar los objetos


# Regla para construir todos los ejecutables
all: $(EXECUTABLES)

# Reglas para cada ejecutable

	
	

# Regla para limpiar los archivos objeto y ejecutables
clean:
	rm -f $(OBJECTS) $(EXECUTABLES)
